apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-movj
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-movj
    app.kubernetes.io/part-of: ci10t-777-0095-app
  name: devfile-sample-movj
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-movj
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-movj
    spec:
      containers:
      - image: quay.io/pmacik-testing/ci10t-777-0095-tenant/ci10t-777-0095-app/devfile-sample-movj@sha256:5400c5e9fa056cbd186aef893d1f3bb3bd1bd7155f2210ca0f855e97d81044da
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
